// LaravelReact/resources/js/Pages/Ads/Create.jsx
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, Link, router, useForm } from "@inertiajs/react";
import PrimaryButton from "@/Components/PrimaryButton";

const Create = ({ auth }) => {
    const { data, setData, post, processing, errors } = useForm({
        title: "",
        description: "",
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        router.post("/ads", data);
    };

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={
                <div className="flex">
                    <Link href="/ads">
                        <h2 className="font-semibold text-xl text-gray-800 leading-tight">
                            My ads
                        </h2>
                    </Link>
                    <h2 className="font-semibold text-xl text-gray-800 leading-tight">
                        {" -> "}
                    </h2>
                    <Link href="/ads/create">
                        <h2 className="font-semibold text-xl text-blue-600 leading-tight">
                            Create
                        </h2>
                    </Link>
                </div>
            }
        >
            <Head title="My ads" />
            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            <p className="mb-2">New ad</p>
                            <div className="flex justify-between mb-8">
                                <form onSubmit={(e) => handleSubmit(e)}>
                                    <div className="flex justify-center flex-col">
                                        <label htmlFor="title">Title:</label>
                                        <input
                                            type="text"
                                            id="title"
                                            name="title"
                                            className="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                            value={data.title}
                                            onChange={(e) =>
                                                setData("title", e.target.value)
                                            }
                                        />
                                        {errors.title && (
                                            <div className="text-red-300">
                                                {errors.title}
                                            </div>
                                        )}
                                    </div>
                                    <div className="flex justify-center flex-col mt-6">
                                        <label htmlFor="description">
                                            Description
                                        </label>
                                        <textarea
                                            id="description"
                                            name="description"
                                            className="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                            value={data.description}
                                            onChange={(e) =>
                                                setData(
                                                    "description",
                                                    e.target.value
                                                )
                                            }
                                        />
                                    </div>
                                    {errors.description && (
                                        <div className="text-red-300">
                                            {errors.description}
                                        </div>
                                    )}
                                    <PrimaryButton className="mt-2">
                                        Create
                                    </PrimaryButton>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
};

export default Create;

// LaravelVue/resources/js/Pages/Dashboard/Ads/Create.vue
<script setup>
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { Head, Link } from "@inertiajs/vue3";
import Button from "../../../CustomComponents/Button.vue";
import { reactive, watch } from "vue";
import { router } from "@inertiajs/vue3";

defineProps({ errors: Object });

const form = reactive({
    title: null,
    description: null,
    price: null,
    location: null,
    image: null,
});

const handleSubmit = () => {
    router.post("/dashboard/ads", form);
};
</script>

<template>
    <Head title="Create ad" />
    <AuthenticatedLayout>
        <template #header>
            <div class="flex">
                <Link href="/dashboard">
                    <h2
                        class="font-semibold text-xl text-gray-800 leading-tight cursor-pointer"
                    >
                        Dashboard ->
                    </h2>
                </Link>
                <h2
                    class="font-semibold text-xl text-blue-600 leading-tight cursor-pointer"
                >
                    Create ad
                </h2>
            </div>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900">
                        <form @submit.prevent="handleSubmit">
                            <div class="flex flex-col mb-4">
                                <label for="title" class="text-xl"
                                    >Title*</label
                                >
                                <input
                                    id="title"
                                    v-model="form.title"
                                    class="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                />
                                <div v-if="errors.title">
                                    {{ errors.title }}
                                </div>
                            </div>
                            <div class="flex flex-col mb-4">
                                <label for="description" class="text-xl"
                                    >Description</label
                                >
                                <input
                                    id="description"
                                    v-model="form.description"
                                    class="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                />
                                <div v-if="errors.description">
                                    {{ errors.description }}
                                </div>
                            </div>
                            <div class="flex flex-col mb-4">
                                <label for="price" class="text-xl"
                                    >Price*</label
                                >
                                <input
                                    id="price"
                                    v-model="form.price"
                                    class="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                />
                                <div v-if="errors.price">
                                    {{ errors.price }}
                                </div>
                            </div>
                            <div class="flex flex-col mb-4">
                                <label for="location" class="text-xl"
                                    >Location</label
                                >
                                <input
                                    id="location"
                                    v-model="form.location"
                                    class="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                />
                                <div v-if="errors.location">
                                    {{ errors.location }}
                                </div>
                            </div>
                            <div class="flex flex-col mb-4">
                                <label for="image" class="text-xl"
                                    >Image URL</label
                                >
                                <input
                                    id="image"
                                    v-model="form.image"
                                    class="border-b-gray-600 border-t-0 border-x-0 border-gray-300 p-2"
                                />
                                <div v-if="errors.image">
                                    {{ errors.image }}
                                </div>
                            </div>
                            <Button buttonType="secondary">Create ad</Button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
